### PR TITLE
Bug Fix - Support for Windows and Unix-base Systems End Of Line Characters

### PR DESCRIPTION
**Pull request by jorg3lopez**
# Clean Keys from End of Line Characters

 This PR fixes a new bug that was detected when using docker to run our application in Windows. The bug was related to the parsing of our public key. When Running TI in docker, in a Windows environment, the key had `\r\n` characters do to the way Windows end of line characters work.

## Solution
Normalize key from `\r\n to \n` and then clean the key from `\n`.

## How to Test
- run `./gradlew shadowJar`
- run `docker compose up --build` to spin up the containers
- request an access token to our auth endpoint
- make sure request is successful
- stop containers by running `docker compose down`
- run `./gradlew :app:test && ./gradlew :shared:test && ./gradlew :etor:test && ./e2e-execute.sh`

## Issue
#1244 

## Checklist

- [x] I have added tests to cover my changes

### CODE REVIEW

**Comment by tjohnson7021** [comment]
@jorg3lopez 

**Just a note for testing this PR on Mac:**

⚠️ I got this error message when running: 
`./gradlew :app:test && ./gradlew :shared:test && ./gradlew :etor:test && ./gradlew e2e-execute.sh`


#### **Error**
```
FAILURE: Build failed with an exception.
* What went wrong:
Task 'e2e-execute.sh' not found in root project 'trusted-intermediary' and its subprojects.
```

✅ But, if I run this `./gradlew :app:test && ./gradlew :shared:test && ./gradlew :etor:test && cd .. && ./gradlew e2e-execute.sh` all the test pass.

**Review by tjohnson7021 — DISMISSED** [review]

**Comment by jbiskie** [comment]
> @jorg3lopez
> 
> **Just a note for testing this PR on Mac:**
> 
> ⚠️ I got this error message when running: `./gradlew :app:test && ./gradlew :shared:test && ./gradlew :etor:test && ./gradlew e2e-execute.sh`
> #### **Error**
> 
> ```
> FAILURE: Build failed with an exception.
> * What went wrong:
> Task 'e2e-execute.sh' not found in root project 'trusted-intermediary' and its subprojects.
> ```
> 
> ✅ But, if I run this `./gradlew :app:test && ./gradlew :shared:test && ./gradlew :etor:test && cd .. && ./gradlew e2e-execute.sh` all the test pass.

In Windows, the first version fails, and I get a `bash: ./gradlew: No such file or directory` when I run the second.  This works ok for me, though: `./gradlew :app:test && ./gradlew :shared:test && ./gradlew :etor:test && ./e2e-execute.sh`

**Review by jbiskie — APPROVED** [review]
Tested successfully in Windows with and without Docker

**Comment by tjohnson7021** [comment]
> > **Just a note for testing this PR on Mac:**
> > ⚠️ I got this error message when running: `./gradlew :app:test && ./gradlew :shared:test && ./gradlew :etor:test && ./gradlew e2e-execute.sh`
> > #### **Error**
> > ```
> > FAILURE: Build failed with an exception.
> > * What went wrong:
> > Task 'e2e-execute.sh' not found in root project 'trusted-intermediary' and its subprojects.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ✅ But, if I run this `./gradlew :app:test && ./gradlew :shared:test && ./gradlew :etor:test && cd .. && ./gradlew e2e-execute.sh` all the test pass.
> 
> In Windows, the first version fails, and I get a `bash: ./gradlew: No such file or directory` when I run the second. This works ok for me, though: `./gradlew :app:test && ./gradlew :shared:test && ./gradlew :etor:test && ./e2e-execute.sh`

Using the command that Joel used I no longer get directory errors, but I do get errors in MetadataTest. See below:

`./gradlew :app:test && ./gradlew :shared:test && ./gradlew :etor:test && ./e2e-execute.sh`:

```
BUILD SUCCESSFUL in 23s
15 actionable tasks: 15 executed
~/Repos/FlexionRepos/trusted-intermediary/trusted-intermediary/app ~/Repos/FlexionRepos/trusted-intermediary/trusted-intermediary
Starting API
API starting at PID 32074
~/Repos/FlexionRepos/trusted-intermediary/trusted-intermediary
Waiting for API to respond
API is responding
Running the end-to-end tests
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.9/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build

> Task :e2e:test

ConsolidatedSummaryTest > a consolidated summary is returned from the ETOR consolidated summary endpoint FAILED
    org.spockframework.runtime.ConditionFailedWithExceptionError at ConsolidatedSummaryTest.groovy:35
        Caused by: groovy.lang.MissingPropertyException at ConsolidatedSummaryTest.groovy:35

MetadataTest > a metadata response is returned from the ETOR metadata endpoint FAILED
    java.lang.NullPointerException at MetadataTest.groovy:37

MetadataTest > a metadata response is returned from the ETOR metadata endpoint for results FAILED
    java.lang.NullPointerException at MetadataTest.groovy:81

MetadataTest > a 404 is returned when there is no metadata for a given ID FAILED
    org.spockframework.runtime.SpockComparisonFailure at MetadataTest.groovy:116

MetadataTest > linked id for the corresponding message is included when retrieving linked metadata FAILED
    java.lang.NullPointerException at MetadataTest.groovy:155

MetadataTest > a metadata order is not linked when the corresponding linking fields do not match FAILED
    java.lang.NullPointerException at MetadataTest.groovy:194

24 tests completed, 6 failed

> Task :e2e:test FAILED
```

**Review by tjohnson7021 — APPROVED** [review]

**Comment by jorg3lopez** [comment]
> @jorg3lopez
> 
> **Just a note for testing this PR on Mac:**
> 
> ⚠️ I got this error message when running: `./gradlew :app:test && ./gradlew :shared:test && ./gradlew :etor:test && ./gradlew e2e-execute.sh`
> 
> #### **Error**
> ```
> FAILURE: Build failed with an exception.
> * What went wrong:
> Task 'e2e-execute.sh' not found in root project 'trusted-intermediary' and its subprojects.
> ```
> 
> ✅ But, if I run this `./gradlew :app:test && ./gradlew :shared:test && ./gradlew :etor:test && cd .. && ./gradlew e2e-execute.sh` all the test pass.

Good catch, it should be `./e2e-execute.sh`. I will edit the PR

**Comment by jorg3lopez** [comment]
All unsigned commits were put into one signed commit and then force pushed.

**Comment by hcp4** [comment]
Completed test using docker.

**Pull request merged**
