### PR TITLE
ADR on the Project Structure

### PR DESCRIPTION
**Pull request by halprin**
# ADR on the Project Structure

Created an ADR describing our updated project structure.

## Issue

_None_.

## Checklist

- [x] I have updated the documentation accordingly

### CODE REVIEW

**Review by sfradkin — APPROVED** [review]
Not sure if you'd like to include any information about the choice for using a plugin style architecture.  Do we have documentation somewhere on what is required to create another plugin and some example of why another plugin would be needed?

**Comment by halprin** [comment]
> Not sure if you'd like to include any information about the choice for using a plugin style architecture. Do we have documentation somewhere on what is required to create another plugin and some example of why another plugin would be needed?

We have an existing [ADR](https://github.com/CDCgov/trusted-intermediary/blob/main/adr/006-domain-plugin.md) on the plugin paradigm.  It doesn't exactly call out the reasons one would make a new plugin for.  It alludes to the fact that you would make one for a separate business domain.

**Comment by sfradkin** [comment]
Excellent

**Review by jcrichlake — COMMENTED** [review]
lgtm

**Pull request merged**
